markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class   : 'syntax'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

